export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpeg",
    username: "Pranjal Patel",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpeg",
    username: "Abhijith Hari",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "Aditya Bikram",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpeg",
    username: "Aryan Jain",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpeg",
    username: "Rajesh Nagar",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpeg",
    username: "Sima Sharma",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpeg",
    username: "Aryabhat",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpeg",
    username: "Joshua Davis",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpeg",
    username: "Tanya Jayanti",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "Jasmine Shankar",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Village view🌾🌾🌾",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "The view is amazing🌊",
    photo: "assets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "#kolkata",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    desc: "Had a Great time with family❤️",
    photo: "assets/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    desc: "Rap Rap Rap",
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    desc: "Wow",
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Virat bhai🏏",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    desc: "🔥🔥",
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Pepsi piyo",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    desc: "Felt good, might delete later!",
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
